apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: customers
        image: charishmatamarana/uber_eats_backend-customers:latest
        ports:
        - containerPort: 8001  # Adjust to your Django port
      - name: order
        image: charishmatamarana/uber_eats_backend-order:latest
        ports:
        - containerPort: 8002  # Adjust to your Django port
      - name: restaurants
        image: charishmatamarana/uber_eats_backend-restaurants:latest
        ports:
        - containerPort: 8003  # Adjust to your Django port
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config


